### PR TITLE
Individual Cart Fix

### PR DESCRIPTION
**Pull request by Blahdidah**
Changes for individual Assignment as well as setting default to single quotations

### CODE REVIEW

**Comment by crewsbd** [comment]
This works with a clean local storage or if there is an array, but it fails if there is some other type of object stored in so-cart. You could have it explicitly check if the stored item is an array with Array.isArray(existingCart). That way, if anything other than a list is in there, you can make the new list.

**Comment by crewsbd** [comment]
Maybe we should go ahead and fix all the double quotes while we are at it. The prettier formatter is in conflict with the linter. If you add this to .prettierrc, it will stop complaining about single quotes.
    {
        "singleQuote": true
    }

**Comment by crewsbd** [comment]
We could also change line 11 in package.json to format mjs files too. Those were getting flagged by prettier. 

"format": "prettier --ignore-path ./.gitignore --write \"./**/*.{html,json,js,mjs,ts,css}\"",

and line 10 change to

"lint": "eslint *.js src/**/*.js src/**/*.mjs",

**Comment by Blahdidah** [comment]
> Maybe we should go ahead and fix all the double quotes while we are at it. The prettier formatter is in conflict with the linter. If you add this to .prettierrc, it will stop complaining about single quotes. { "singleQuote": true }



> We could also change line 11 in package.json to format mjs files too. Those were getting flagged by prettier.
> 
> "format": "prettier --ignore-path ./.gitignore --write "./**/*.{html,json,js,mjs,ts,css}"",
> 
> and line 10 change to
> 
> "lint": "eslint _.js src/**/_.js src/**/*.mjs",

why would we m ake these changes? they remove the wildcards and escape characters?

**Comment by Blahdidah** [comment]
I updated my cart code as you mentioned Brian. For some reason my double quote stuff didn't stick, so i fixed it again. I'm getting no formatting errors with prettier, and no errors with lint.

**Comment by crewsbd** [comment]
> > Maybe we should go ahead and fix all the double quotes while we are at it. The prettier formatter is in conflict with the linter. If you add this to .prettierrc, it will stop complaining about single quotes. { "singleQuote": true }
> 
> > We could also change line 11 in package.json to format mjs files too. Those were getting flagged by prettier.
> > "format": "prettier --ignore-path ./.gitignore --write "./**/*.{html,json,js,mjs,ts,css}"",
> > and line 10 change to
> > "lint": "eslint _.js src/**/_.js src/**/*.mjs",
> 
> why would we m ake these changes? they remove the wildcards and escape characters?

They just add the mjs files to the linter and prettier formatter. For example. utils.mjs still has double quotes and prettier is marking them red for me.

**Comment by crewsbd** [comment]
Consider me signed off for the merge.

**Pull request merged**
